on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vercel:
    name: Deploy frontend preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Deploy preview to Vercel
        run: npx vercel --token ${{secrets.VERCEL_TOKEN}}
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  heroku:
    name: Deploy backend preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_PREVIEW_APP_NAME}}
          branch: ${{}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
