name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  tests:
    name: Running all tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Unit tests
        run: yarn test:all
  vercel:
    name: Deploy frontend
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Deploy to Vercel
        run: npx vercel --token ${{secrets.VERCEL_TOKEN}} --prod
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  heroku:
    name: Deploy backend
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          branch: origin/master
          heroku_email: ${{secrets.HEROKU_EMAIL}}
